### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by LiudmylaP** [LiudmylaP/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Panineduard** [comment]
I am the most successful person. It is well.


ср, 6 мая 2020 г., 12:26 LiudmylaP <notifications@github.com>:

**Comment by LiudmylaP** [comment]
Thanks
