### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by LiudmylaP** [LiudmylaP/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Panineduard** [comment]
Good job 👏

ср, 6 мая 2020 г., 12:26 LiudmylaP <notifications@github.com>:
